// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8TyWryqqwT3t409tgLdoaWLABaE-7MA',
    appId: '1:958198263543:web:e4ef783d11359b29da6df2',
    messagingSenderId: '958198263543',
    projectId: 'memo-dc08a',
    authDomain: 'memo-dc08a.firebaseapp.com',
    storageBucket: 'memo-dc08a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUoPhuRLaZzxWus-at4k8OvIPJmxNaEc',
    appId: '1:958198263543:android:ea9c9fbcf3250c61da6df2',
    messagingSenderId: '958198263543',
    projectId: 'memo-dc08a',
    storageBucket: 'memo-dc08a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvymc5PnXaepWmOaBK4qXUIp_O_Arh2Ec',
    appId: '1:958198263543:ios:0319c37be7961715da6df2',
    messagingSenderId: '958198263543',
    projectId: 'memo-dc08a',
    storageBucket: 'memo-dc08a.firebasestorage.app',
    iosBundleId: 'com.example.memo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvymc5PnXaepWmOaBK4qXUIp_O_Arh2Ec',
    appId: '1:958198263543:ios:0319c37be7961715da6df2',
    messagingSenderId: '958198263543',
    projectId: 'memo-dc08a',
    storageBucket: 'memo-dc08a.firebasestorage.app',
    iosBundleId: 'com.example.memo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL8TyWryqqwT3t409tgLdoaWLABaE-7MA',
    appId: '1:958198263543:web:977c72bf530b61c2da6df2',
    messagingSenderId: '958198263543',
    projectId: 'memo-dc08a',
    authDomain: 'memo-dc08a.firebaseapp.com',
    storageBucket: 'memo-dc08a.firebasestorage.app',
  );
}
